import { CampaignMission } from '../types/game';

export const CAMPAIGN_MISSIONS: CampaignMission[] = [
  {
    id: 'day1_mcpherson',
    day: 1,
    date: 'July 1, 1863 - 09:30 AM',
    title: 'The Battle Opens: McPherson\'s Ridge',
    subtitle: 'Hold the Chambersburg Pike against Heth\'s advancing division',
    location: 'McPherson\'s Woods & Lutheran Seminary',
    briefing: 'General Heth\'s Confederate division is marching down the Chambersburg Pike in search of supplies and shoes. General Buford\'s cavalry and the Iron Brigade must hold the high ground until Reynolds\' 1st Corps arrives. Form the firing line behind the rail fences and hold the timber line!',
    unionObjective: 'Repel 3 waves of Confederate skirmishers, destroy the forward ammo wagon, and eliminate the advancing Rebel Captain.',
    confederateObjective: 'Overrun the Iron Brigade\'s defensive line along McPherson\'s Ridge and capture the Seminary high ground.',
    environmentType: 'MACPHERSON',
    skyColor: 0x87CEEB,
    fogColor: 0xD8CBB5,
    fogDensity: 0.012,
    sunPosition: [100, 150, -80],
    waves: 3,
    bossName: 'Capt. Archer (Confederate Line Officer)',
    estimatedTime: '4-5 min',
    parTimeSeconds: 120,
    historicalDispatches: [
      { wave: 1, title: 'DISPATCH • 09:30 AM', text: 'Buford\'s dismounted troopers engage Archer\'s brigade along Willoughby Run!' },
      { wave: 2, title: 'DISPATCH • 10:15 AM', text: 'General John F. Reynolds arrives with the Iron Brigade: "Forward men, for God\'s sake, forward!"' },
      { wave: 3, title: 'DISPATCH • 11:00 AM', text: 'Iron Brigade envelopes Archer in Herbst Woods! Repel the final Confederate thrust!' },
    ],
  },
  {
    id: 'day2_roundtop',
    day: 2,
    date: 'July 2, 1863 - 04:30 PM',
    title: 'Chamberlain\'s Stand: Little Round Top',
    subtitle: 'The extreme left flank of the Union Army of the Potomac',
    location: 'Little Round Top & Devil\'s Den Boulder Valley',
    briefing: 'Hood\'s Texans and Law\'s 15th Alabama are surging up the rocky boulder-strewn slopes of Little Round Top! Colonel Joshua Chamberlain and the 20th Maine hold the extreme flank. When musket ammunition runs dry: FIX BAYONETS and sweep down the hill!',
    unionObjective: 'Defend the summit boulders, eliminate enemy sharpshooters in Devil\'s Den, and lead the Great Right Wheel Bayonet Charge!',
    confederateObjective: 'Scale the rocky heights of Little Round Top, silence the Union signal corps, and roll up Meade\'s flank.',
    environmentType: 'ROUND_TOP',
    skyColor: 0xE8A87C,
    fogColor: 0xC38D9E,
    fogDensity: 0.015,
    sunPosition: [-120, 70, 100],
    waves: 4,
    bossName: 'Col. Oates (15th Alabama Commander)',
    estimatedTime: '5-6 min',
    parTimeSeconds: 150,
    historicalDispatches: [
      { wave: 1, title: 'DISPATCH • 04:30 PM', text: 'General Warren spots Hood\'s division flanking through Plum Run valley!' },
      { wave: 2, title: 'DISPATCH • 05:15 PM', text: '15th Alabama lunges up the boulder crest! 20th Maine refuses the line at right angles!' },
      { wave: 3, title: 'DISPATCH • 06:00 PM', text: 'Cartridge boxes are empty! Chamberlain orders: "BAYONETS! FIX BAYONETS!"' },
      { wave: 4, title: 'DISPATCH • 06:30 PM', text: 'The Great Right Wheel charge sweeps down Little Round Top into the valley!' },
    ],
  },
  {
    id: 'day2_wheatfield_night',
    day: 2,
    date: 'July 2, 1863 - 09:00 PM',
    title: 'Whirlpool of Blood: The Wheatfield at Night',
    subtitle: 'Trench fighting and smoke-choked woodland warfare under moonlight',
    location: 'The Wheatfield & Culp\'s Hill Entrenchments',
    briefing: 'Darkness falls over the blood-soaked amber wheat. Gunsmoke hangs like a thick blanket over the field, lit only by cannon muzzle flashes and burning supply caissons. The lines are broken and fighting is at point-blank range in the woods.',
    unionObjective: 'Navigate the smoke-filled woods, locate and destroy 3 enemy ammo caissons, and secure the stone wall.',
    confederateObjective: 'Slip through the Union defensive gap in the darkness and capture the supply wagons before dawn.',
    environmentType: 'WHEATFIELD_NIGHT',
    skyColor: 0x0A0F1D,
    fogColor: 0x1A2238,
    fogDensity: 0.025,
    sunPosition: [50, 20, -50],
    waves: 3,
    bossName: 'Maj. Pelham (Rebel Artillery Commander)',
    estimatedTime: '4-5 min',
    parTimeSeconds: 130,
    historicalDispatches: [
      { wave: 1, title: 'DISPATCH • 09:00 PM', text: 'Muzzle flashes illuminate the wheat! The field changes hands for the sixth time.' },
      { wave: 2, title: 'DISPATCH • 09:45 PM', text: 'Irish Brigade and Caldwell\'s division enter the swirling smoke whirlpool!' },
      { wave: 3, title: 'DISPATCH • 10:30 PM', text: 'Secure the stone fence line under heavy moonlight artillery barrage!' },
    ],
  },
  {
    id: 'day3_pickett',
    day: 3,
    date: 'July 3, 1863 - 02:45 PM',
    title: 'The High Water Mark: Pickett\'s Charge',
    subtitle: 'The grand climax of the American Civil War',
    location: 'The Angle & The Copse of Trees (Cemetery Ridge)',
    briefing: 'Following the greatest artillery bombardment in American history with 150 massed Confederate guns, 12,500 soldiers under Generals Pickett, Pettigrew, and Trimble step out of the treeline. They march across one mile of open farmland directly toward the stone wall at The Angle.',
    unionObjective: 'Command Cushing\'s 12-Pounder Battery, lay down triple canister fire, and repel the massive final charge at the Copse of Trees!',
    confederateObjective: 'Advance under relentless cannon fire, leap over the stone wall at The Angle, and breach the Union line!',
    environmentType: 'THE_ANGLE',
    skyColor: 0xD4AF37,
    fogColor: 0xBA9F72,
    fogDensity: 0.016,
    sunPosition: [0, 180, 80],
    waves: 5,
    bossName: 'Gen. Lewis Armistead (High Water Mark Vanguard)',
    estimatedTime: '6-8 min',
    parTimeSeconds: 180,
    historicalDispatches: [
      { wave: 1, title: 'DISPATCH • 01:00 PM', text: '150 Confederate guns open fire on Cemetery Ridge! Cushing\'s battery responds!' },
      { wave: 2, title: 'DISPATCH • 02:45 PM', text: 'The Virginia line steps out of Spangler Woods: 12,500 bayonets glistening in the sun!' },
      { wave: 3, title: 'DISPATCH • 03:15 PM', text: 'Union artillery switches to double canister! The line converges at The Angle!' },
      { wave: 4, title: 'DISPATCH • 03:30 PM', text: 'General Lewis Armistead places his hat on his sword and breaches the low stone wall!' },
      { wave: 5, title: 'DISPATCH • 03:45 PM', text: 'Hand-to-hand combat at the Copse of Trees! Repel the High Water Mark of the Confederacy!' },
    ],
  },
];
