import { ClassDefinition } from '../types/game';

export const CHARACTER_CLASSES: ClassDefinition[] = [
  {
    id: 'INFANTRY',
    title: 'Rifleman (Line Infantry)',
    role: 'Balanced Frontline Combat',
    description: 'The iron backbone of the regiment. Master of disciplined rifle-musket volleys and ferocious bayonet counter-charges.',
    primaryWeaponUnion: 'springfield_1861',
    primaryWeaponConfed: 'enfield_1853',
    passiveDescription: '+15% Sprint Speed & +20 Max Stamina. +100% Bayonet melee piercing damage.',
    abilityName: 'Bayonet Charge Surge',
    abilityKey: 'G or F',
    abilityDescription: 'Gain a +70% sprint speed burst for 6 seconds with automatic lethal bayonet thrusts on contact and instant musket chamber reload on kill.',
    abilityCooldown: 18,
    abilityDuration: 6,
  },
  {
    id: 'SHARPSHOOTER',
    title: 'Sharpshooter (Sniper)',
    role: 'Long-Range Marksmanship',
    description: 'Elite marksman equipped with telescopic optics and hexagonal rifling capable of eliminating hostile officers from extreme distances.',
    primaryWeaponUnion: 'spencer_repeater',
    primaryWeaponConfed: 'whitworth_sharpshooter',
    passiveDescription: 'Zero ADS sway, 2.5x Critical Headshot multiplier, and extended engagement radar range.',
    abilityName: 'Eagle Eye Bullet-Time',
    abilityKey: 'G',
    abilityDescription: 'Enter extreme focus for 5 seconds: enemy time slows by 60%, granting 100% pinpoint hitscan precision and 3x headshot scoring.',
    abilityCooldown: 20,
    abilityDuration: 5,
  },
  {
    id: 'MEDIC',
    title: 'Field Surgeon (Support)',
    role: 'Sustained Vitality & Support',
    description: 'Brave combat medical practitioner trained in battlefield tourniquets, chloroform, and restorative water distribution.',
    primaryWeaponUnion: 'colt_navy_1851',
    primaryWeaponConfed: 'lemat_revolver',
    passiveDescription: 'Starts with 5 Canteen charges (normally 3) and passive +2 HP/sec health regeneration.',
    abilityName: 'Field Triage & Bandage',
    abilityKey: 'G',
    abilityDescription: 'Immediately restores +70 HP, fully refreshes stamina, refills +2 canteen charges, and grants a +30% damage resistance aura for 8 seconds.',
    abilityCooldown: 16,
    abilityDuration: 8,
  },
  {
    id: 'OFFICER',
    title: 'Artillery Officer (Commander)',
    role: 'Heavy Firepower & Tactical Commands',
    description: 'Regimental commander who coordinates artillery batteries, directs massed canister volleys, and rallies wavering troops.',
    primaryWeaponUnion: 'colt_navy_1851',
    primaryWeaponConfed: 'lemat_revolver',
    passiveDescription: 'Artillery charge builds 2x faster from kills and hits. Kills grant double morale score.',
    abilityName: 'Battery Canister Salvo',
    abilityKey: 'G',
    abilityDescription: 'Instantly commands nearby 12-Pounder Napoleon cannons to fire a devastating canister volley, decimating front skirmishers and filling +40% artillery meter.',
    abilityCooldown: 22,
    abilityDuration: 3,
  },
];
