import { WeaponData } from '../types/game';

export const HISTORICAL_WEAPONS: Record<string, WeaponData> = {
  springfield_1861: {
    id: 'springfield_1861',
    name: 'Springfield Model 1861',
    shortName: 'Springfield .58',
    caliber: '.58 Minie Ball',
    damage: 95,
    fireRate: 0.35,
    reloadTime: 3.2,
    authenticReloadTime: 12.0,
    magazineSize: 1,
    currentAmmo: 1,
    reserveAmmo: 40,
    accuracy: 0.94,
    range: 500,
    hasBayonet: true,
    description: 'The standard issue rifled musket of the United States Army. Lethal, highly accurate with devastating Minie ball expansion.',
    historicalNote: 'Over 1,000,000 units produced. The signature sound and smoke of Union infantry volleys at Gettysburg.',
  },
  enfield_1853: {
    id: 'enfield_1853',
    name: 'Pattern 1853 Enfield',
    shortName: 'Enfield .577',
    caliber: '.577 Pritchett Ball',
    damage: 98,
    fireRate: 0.35,
    reloadTime: 3.3,
    authenticReloadTime: 12.5,
    magazineSize: 1,
    currentAmmo: 1,
    reserveAmmo: 40,
    accuracy: 0.93,
    range: 550,
    hasBayonet: true,
    description: 'Imported British rifled musket favored by the Army of Northern Virginia. Renowned for ruggedness and stopping power.',
    historicalNote: 'Carried in large numbers across the fields of Gettysburg by General Lee\'s advancing divisions.',
  },
  colt_navy_1851: {
    id: 'colt_navy_1851',
    name: 'Colt 1851 Navy Revolver',
    shortName: 'Colt .36 Navy',
    caliber: '.36 Percussion',
    damage: 52,
    fireRate: 3.2,
    reloadTime: 2.8,
    authenticReloadTime: 7.5,
    magazineSize: 6,
    currentAmmo: 6,
    reserveAmmo: 36,
    accuracy: 0.86,
    range: 75,
    hasBayonet: false,
    description: 'Six-shot cap-and-ball single-action revolver. Rapid close-quarters officer defense weapon.',
    historicalNote: 'Carried in the holsters of commanders and cavalrymen in fierce hand-to-hand combat at the Copse of Trees.',
  },
  lemat_revolver: {
    id: 'lemat_revolver',
    name: 'LeMat "Grapeshot" Revolver',
    shortName: 'LeMat 9-Shot',
    caliber: '.42 Caliber + 20-Ga Buckshot',
    damage: 58,
    fireRate: 2.6,
    reloadTime: 3.5,
    authenticReloadTime: 9.0,
    magazineSize: 9,
    currentAmmo: 9,
    reserveAmmo: 45,
    accuracy: 0.82,
    range: 65,
    hasBayonet: false,
    description: '9-shot cylinder surrounding a secondary 20-gauge central smoothbore shotgun barrel for close-range destruction.',
    historicalNote: 'Favored by Confederate generals like J.E.B. Stuart and P.G.T. Beauregard.',
  },
  whitworth_sharpshooter: {
    id: 'whitworth_sharpshooter',
    name: 'Whitworth Hexagonal Sniper',
    shortName: 'Whitworth .451',
    caliber: '.451 Hexagonal',
    damage: 145,
    fireRate: 0.28,
    reloadTime: 3.8,
    authenticReloadTime: 14.0,
    magazineSize: 1,
    currentAmmo: 1,
    reserveAmmo: 25,
    accuracy: 0.99,
    range: 1200,
    hasBayonet: false,
    description: 'Legendary long-range precision rifle with hexagonal rifling and brass telescopic sight. One-shot kill precision.',
    historicalNote: 'Used by Confederate sharpshooters at Devil\'s Den targeting Union officers on Little Round Top.',
  },
  spencer_repeater: {
    id: 'spencer_repeater',
    name: 'Spencer 1860 Repeating Rifle',
    shortName: 'Spencer 7-Shot',
    caliber: '.56-56 Rimfire',
    damage: 72,
    fireRate: 1.8,
    reloadTime: 2.4,
    authenticReloadTime: 5.5,
    magazineSize: 7,
    currentAmmo: 7,
    reserveAmmo: 42,
    accuracy: 0.91,
    range: 300,
    hasBayonet: false,
    description: 'Revolutionary 7-round lever-action repeater. Unprecedented fire rate on the Civil War battlefield.',
    historicalNote: 'General George Armstrong Custer\'s Michigan cavalry brigade used Spencers to repel Stuart\'s cavalry at East Cavalry Field.',
  },
};
